### ISSUE TITLE
New Kirby Editor not working inside Builder 

### ISSUE THREAD

**Issue by HashandSalt** [TimOetting/kirby-builder#132]
Bastian's new Editor plugin does not seem to work inside a Builder block. Unsure if the fix lies with the Builder plugin or the Editor. See issue on the Editor repo...

https://github.com/getkirby/editor/issues/67

**Comment by samnabi** [comment]
It has the same issue within a structure field, so I think this should be addressed by the Editor plugin.

**Comment by findthebug** [comment]
Same here.

Kirby 3.2.4
Builder 2.0 (latest, always update via composer)

![Bildschirmfoto 2019-09-11 um 13 18 34](https://user-images.githubusercontent.com/5121132/64758355-b13b9b00-d534-11e9-8fd3-d9b93064df1b.png)
![Bildschirmfoto 2019-09-11 um 13 18 27](https://user-images.githubusercontent.com/5121132/64758356-b13b9b00-d534-11e9-8c51-a59b067b2f12.png)

**Comment by luxlogica** [comment]
@TimOetting I believe this was identified as an issue with the Editor, and has been fixed in Kirby 3.3. + Editor 1.0. To make it work, just use the `pretty: false` option in the Editor field.

This issue can now be closed! :)

**Comment by RobertCordes** [comment]
@TimOetting There is still an error when using the editor inside builder. When I select the image block inside the editor and try to **select** an image, I get the following error message:

> Invalid file model type: kirby-builder/pages/mypage/fields
