### ISSUE TITLE
[Bug] Blocks Are Not Draggable - and Not Sortable

### ISSUE THREAD

**Issue by luxlogica** [TimOetting/kirby-builder#65]
Although the blocks show with a drag handle on the left, the drag and sort functionality is not working - blocks cannot be dragged at all, and therefore cannot be sorted.

**Comment by TimOetting** [comment]
Hey @luxlogica . I can not reproduce this probem. I am able to move and sort the blocks. What browser are you using? Can you give me an example blueprint?

**Comment by luxlogica** [comment]
Hey, @TimOetting, thank you for the quick response. It seems to be a **Safari** issue: I can drag the blocks on Chrome and Firefox, but they're stuck in Safari.

Using MacOS Mojave and the latest Safari.

**Comment by thomasfahrland** [comment]
@luxlogica i can reproduce this after a test in Safari on MacOS Mojave.

**Comment by TimOetting** [comment]
This issue will be solved as soon as Kirby 3.0.1 is out. For now, drag&drop is still not working on Safari.

**Comment by luxlogica** [comment]
@TimOetting, is this fixed now?

**Comment by TimOetting** [comment]
Yep, but as I mentioned, only with Kirby 3.0.1

**Comment by hmccloy** [comment]
Unfortunately there is still an issue with Safari: dragging blocks with child elements cause the browser to crash. Tested with Kirby 3.2.4, Builder 2.0.13 and Safari 12.1.1 (Mojave)

**Comment by evvvritt** [comment]
For anyone else, I thought drag-reorder was also broken but it actually just requires you hover your dragged cursor inside/over the white area of a block. (As opposed to over the other handles of other blocks)
